name: adaptive

channels:
  - conda-forge

dependencies:
  - python=3.7.3
  - sortedcollections=1.1.2
  - scikit-optimize=0.5.2
  - scipy=1.2.1
  - holoviews=1.11.3
  - bokeh=1.0.4
  - plotly=3.9.0
  - ipywidgets=7.4.2
  - pip:
    - git+https://github.com/basnijholt/jupyter-sphinx.git@widgets_execute
    - sphinx_fontawesome==0.0.6
    - m2r==0.2.1
